// ecosystem.config.js
module.exports = {
  apps: [
    {
      name: 'api-gateway',
      script: 'dist/apps/api-gateway/main.js',
      error_file: 'logs/api-gateway-error.log',
      out_file: 'logs/api-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.API_GATEWAY_PORT || 3000,
        JWT_SECRET: process.env.JWT_SECRET,
        ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,
        REDIS_URL: process.env.REDIS_URL,
        AUTH_SERVICE_HOST: process.env.AUTH_SERVICE_HOST || 'localhost',
        AUTH_SERVICE_PORT: process.env.AUTH_SERVICE_PORT || 3002,
        USER_SERVICE_HOST: process.env.USER_SERVICE_HOST || 'localhost',
        USER_SERVICE_PORT: process.env.USER_SERVICE_PORT || 3001,
        GYM_SERVICE_HOST: process.env.GYM_SERVICE_HOST || 'localhost',
        GYM_SERVICE_PORT: process.env.GYM_SERVICE_PORT || 3003,
        REALTIME_SERVICE_HOST: process.env.REALTIME_SERVICE_HOST || 'localhost',
        REALTIME_SERVICE_PORT: process.env.REALTIME_SERVICE_PORT || 3004,
      },
    },
    {
      name: 'user-service',
      script: 'dist/apps/user-service/main.js',
      error_file: 'logs/user-service-error.log',
      out_file: 'logs/user-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.USER_SERVICE_PORT || 3001,
        DB_HOST: process.env.USER_DB_HOST,
        DB_PORT: process.env.USER_DB_PORT || 5432,
        DB_USER: process.env.USER_DB_USER,
        DB_PASS: process.env.USER_DB_PASS,
        DB_NAME: process.env.USER_DB_NAME || 'postgres',
        JWT_SECRET: process.env.JWT_SECRET,
      },
    },
    {
      name: 'auth-service',
      script: 'dist/apps/auth-service/main.js',
      error_file: 'logs/auth-service-error.log',
      out_file: 'logs/auth-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.AUTH_SERVICE_PORT || 3002,
        DB_HOST: process.env.AUTH_DB_HOST,
        DB_PORT: process.env.AUTH_DB_PORT || 5432,
        DB_USER: process.env.AUTH_DB_USER,
        DB_PASS: process.env.AUTH_DB_PASS,
        DB_NAME: process.env.AUTH_DB_NAME || 'postgres',
        JWT_SECRET: process.env.JWT_SECRET,
      },
    },
    {
      name: 'gym-service',
      script: 'dist/apps/gym-service/main.js',
      error_file: 'logs/gym-service-error.log',
      out_file: 'logs/gym-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.GYM_SERVICE_PORT || 3003,
        DB_HOST: process.env.GYM_DB_HOST,
        DB_PORT: process.env.GYM_DB_PORT || 5432,
        DB_USER: process.env.GYM_DB_USER,
        DB_PASS: process.env.GYM_DB_PASS,
        DB_NAME: process.env.GYM_DB_NAME || 'postgres',
        JWT_SECRET: process.env.JWT_SECRET,
      },
    },
    {
      name: 'realtime-service',
      script: 'dist/apps/realtime-service/main.js',
      error_file: 'logs/realtime-service-error.log',
      out_file: 'logs/realtime-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.REALTIME_SERVICE_PORT || 3004,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
      },
    },
    {
      name: 'email-service',
      script: 'dist/apps/email-service/main.js',
      error_file: 'logs/email-service-error.log',
      out_file: 'logs/email-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: {
        NODE_ENV: 'production',
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_SECURE: process.env.SMTP_SECURE,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
      },
    },
  ],
};
